In [1]:
# import pandas as pd
# df=pd.read_csv('student_completed_data.csv')
# df

   StudentID          FullName  ...    Location Total Marks
0     PH0001       Alif Rahman  ...      Khulna         300
1     PH0002     Fatima Akhter  ...       Dhaka         271
2     PH0003     Imran Hossain  ...       Dhaka         269
3     PH0004  Jannatul Ferdous  ...      Khulna         270
4     PH0005       Kamal Uddin  ...      Sylhet         254
5     PH0006       Laila Begum  ...      Khulna         272
6     PH0007    Mahmudul Hasan  ...  Chattogram         249
7     PH0008       Nadia Islam  ...      Khulna         246
8     PH0009        Omar Faruq  ...       Dhaka         291
9     PH0010      Priya Sharma  ...       Dhaka         286
10    PH0011      Rahim Sheikh  ...      Sylhet         283
11    PH0012   Sadia Chowdhury  ...      Sylhet         266
12    PH0013      Tanvir Ahmed  ...       Dhaka         248
13    PH0014        Urmi Akter  ...      Sylhet         285
14    PH0015      Wahiduzzaman  ...    Rajshahi         291
15    PH0016      Ziaur Rahman  ...    Rajshahi         234
16    PH0017       Afsana Mimi  ...      Khulna         236
17    PH0018       Babul Ahmed  ...       Dhaka         278
18    PH0019      Faria Rahman  ...      Sylhet         277
19    PH0020       Tariq Hasan  ...      Khulna         253

[20 rows x 8 columns]

In [66]:
data= {
    'Name': ['Mahmudul', 'abbir', 'Talha', 'Mahi', 'Saimum', 'Rifat', 'Nahid', 'Naser', 'Fahim', 'Saif'],
    'City': ['Old Rajshahi', "Savar", "new Dhamrai", "Lakkhipur", "Jamalpur", 'Natore', 'Old Dhamrai', 'New Bogura', 'Bagura', 'Naogaon'],
    'Dept': ['HR', 'IT', 'Finance', 'HR', "Marketing", 'IT' , 'Finance', 'Marketing', 'Finance', 'Marketing'],
    'Salary': [50000, 45000, 56000, 60000, 40000, 35000, 70000, 80000, 30000, 35000]
}
df=pd.DataFrame(data)
## find city Where city contains new word
contains_new=df.loc[df['City'].str.contains("New", case=False)] ## removing case senstitive
contains_new
start_old=df.loc[df['City'].str.contains(r"^Old", case=False)] 
start_old
end_pur=df.loc[df['City'].str.contains(r"pur$", case=False)]
end_pur
## name start with a vowel
vowel=df.loc[df['Name'].str.contains(r"^[AEIOU]", case=False)]
vowel
#multiple 
city=df.loc[df['City'].str.contains(r'new| old', case=False)]
city
##isin
check=df.loc[df['City'].isin(["Savar", 'Bagura', 'Rajshahi'])]
check

    Name    City     Dept  Salary
1  abbir   Savar       IT   45000
8  Fahim  Bagura  Finance   30000

## Column Adding

In [67]:
df['Country']='Bangladesh'
df

       Name          City       Dept  Salary     Country
0  Mahmudul  Old Rajshahi         HR   50000  Bangladesh
1     abbir         Savar         IT   45000  Bangladesh
2     Talha   new Dhamrai    Finance   56000  Bangladesh
3      Mahi     Lakkhipur         HR   60000  Bangladesh
4    Saimum      Jamalpur  Marketing   40000  Bangladesh
5     Rifat        Natore         IT   35000  Bangladesh
6     Nahid   Old Dhamrai    Finance   70000  Bangladesh
7     Naser    New Bogura  Marketing   80000  Bangladesh
8     Fahim        Bagura    Finance   30000  Bangladesh
9      Saif       Naogaon  Marketing   35000  Bangladesh

In [76]:
import pandas as pd
import numpy as np
df=pd.read_csv('student_data.csv')
df
df['Total Marks']=df['Data Structure Marks'] + df['Algorithm Marks'] +df["Python Marks"]
df
df['Got A+']=np.where(df['Algorithm Marks'] >80, 'YES', "NO")
df

   StudentID          FullName  ...  Total Marks  Got A+
0     PH1001       Alif Rahman  ...        258.0     YES
1     PH1002     Fatima Akhter  ...          NaN     YES
2     PH1003     Imran Hossain  ...        261.0     YES
3     PH1004  Jannatul Ferdous  ...        238.0      NO
4     PH1005       Kamal Uddin  ...          NaN      NO
5     PH1006       Laila Begum  ...        228.0      NO
6     PH1007    Mahmudul Hasan  ...          NaN      NO
7     PH1008       Nadia Islam  ...        247.0     YES
8     PH1009        Omar Faruq  ...        220.0      NO
9     PH1010      Priya Sharma  ...        266.0     YES
10    PH1011      Rahim Sheikh  ...          NaN      NO
11    PH1012   Sadia Chowdhury  ...        257.0     YES
12    PH1013      Tanvir Ahmed  ...        229.0      NO
13    PH1014        Urmi Akter  ...          NaN      NO
14    PH1015      Wahiduzzaman  ...        256.0     YES
15    PH1016      Ziaur Rahman  ...          NaN     YES
16    PH1017       Afsana Mimi  ...        273.0     YES
17    PH1018       Babul Ahmed  ...        261.0     YES
18    PH1019      Faria Rahman  ...          NaN      NO
19    PH1020        Nasir Khan  ...        261.0     YES

[20 rows x 11 columns]

In [77]:
## pass in ds
df["Passed In DS"]=np.where(df['Data Structure Marks']>70, 'YES', 'NO')
df

   StudentID          FullName  ...  Got A+  Passed In DS
0     PH1001       Alif Rahman  ...     YES           YES
1     PH1002     Fatima Akhter  ...     YES           YES
2     PH1003     Imran Hossain  ...     YES           YES
3     PH1004  Jannatul Ferdous  ...      NO           YES
4     PH1005       Kamal Uddin  ...      NO            NO
5     PH1006       Laila Begum  ...      NO           YES
6     PH1007    Mahmudul Hasan  ...      NO           YES
7     PH1008       Nadia Islam  ...     YES           YES
8     PH1009        Omar Faruq  ...      NO           YES
9     PH1010      Priya Sharma  ...     YES           YES
10    PH1011      Rahim Sheikh  ...      NO            NO
11    PH1012   Sadia Chowdhury  ...     YES           YES
12    PH1013      Tanvir Ahmed  ...      NO           YES
13    PH1014        Urmi Akter  ...      NO            NO
14    PH1015      Wahiduzzaman  ...     YES           YES
15    PH1016      Ziaur Rahman  ...     YES           YES
16    PH1017       Afsana Mimi  ...     YES           YES
17    PH1018       Babul Ahmed  ...     YES           YES
18    PH1019      Faria Rahman  ...      NO            NO
19    PH1020        Nasir Khan  ...     YES           YES

[20 rows x 12 columns]

In [81]:
df['First Name']=df['FullName'].str.split().str[0]
df

   StudentID          FullName  ...  Passed In DS    First Name
0     PH1001       Alif Rahman  ...           YES          Alif
1     PH1002     Fatima Akhter  ...           YES        Fatima
2     PH1003     Imran Hossain  ...           YES         Imran
3     PH1004  Jannatul Ferdous  ...           YES      Jannatul
4     PH1005       Kamal Uddin  ...            NO         Kamal
5     PH1006       Laila Begum  ...           YES         Laila
6     PH1007    Mahmudul Hasan  ...           YES      Mahmudul
7     PH1008       Nadia Islam  ...           YES         Nadia
8     PH1009        Omar Faruq  ...           YES          Omar
9     PH1010      Priya Sharma  ...           YES         Priya
10    PH1011      Rahim Sheikh  ...            NO         Rahim
11    PH1012   Sadia Chowdhury  ...           YES         Sadia
12    PH1013      Tanvir Ahmed  ...           YES        Tanvir
13    PH1014        Urmi Akter  ...            NO          Urmi
14    PH1015      Wahiduzzaman  ...           YES  Wahiduzzaman
15    PH1016      Ziaur Rahman  ...           YES         Ziaur
16    PH1017       Afsana Mimi  ...           YES        Afsana
17    PH1018       Babul Ahmed  ...           YES         Babul
18    PH1019      Faria Rahman  ...            NO         Faria
19    PH1020        Nasir Khan  ...           YES         Nasir

[20 rows x 13 columns]

In [82]:
## internally %save
df.to_csv('NewData.csv')

## Check Unique & Null

In [100]:
df['FullName'].unique()
df['Data Structure Marks'].unique()
unique_with_nan=len(df['Data Structure Marks'].unique()) ## it works wonly series
unique_with_nan
df['Data Structure Marks'].nunique() ## weorks in dataframe
df.isnull() ## null thakle true return korbe, na thakle false
df['Python Marks'].isnull()
df['Algorithm Marks'].notnull()
## hasnans
df['Algorithm Marks'].hasnans ## this is a statement, will return true or false

True

In [148]:
data= {
    'Name': ['Mahmudul', 'Mahi', 'Talha', 'Mahi', 'Mahmudul', 'Rifat', 'Talha', 'Naser', 'Fahim', 'Mahmudul'],
    'City': ['Old Rajshahi', "Lakkhipur", "Old Dhamrai", "Lakkhipur", "Old Rajshahi", 'Natore', 'Old Dhamrai', 'Bogura', 'Bagura', 'Old Rajshahi'],
    'Dept': ['HR', 'IT', 'Marketing', 'IT', "HR", 'HR' , 'Finance', 'Marketing', 'Finance', 'HR'],
    'Salary': [50000, 35000, 56000, 35000, 50000, 30000, 70000, 40000, 30000, 50000]
}
df1=pd.DataFrame(data)
df1
df1.duplicated()
df1=df1.drop_duplicates(subset='Name', keep='first')
df1

0     88.0
2     85.0
3     82.0
4     95.0
5     78.0
7     85.0
8     76.0
9     88.0
10    91.0
11    87.0
12    79.0
14    84.0
16    93.0
17    85.0
19    89.0
Name: Python Marks, dtype: float64

## Handling Null Values

In [153]:
df=df.dropna(how='all')
python=df.dropna(subset=['Python Marks'])
python

TypeError: Series.dropna() got an unexpected keyword argument 'subset'